name: 'danger-js'

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  danger-js:
    name: Danger.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Danger.js
        uses: danger/danger-js@11.2.8
        env:
          DANGER_GITLAB_API_TOKEN: ${{ secrets.BRO_CHAT_BOT }}
